### ISSUE TITLE
Bind to Ldaps not working under Linux environment

### ISSUE THREAD

**Issue by mihailsidoroff** [flamencist/ldap4net#10]
Hello, i have some problem with connecting to Active Directory using ldaps (port 636) under linux environment(ubuntu).
I call Connect, after that i call Bind (via kerberos), and nothing happens, no errors, no cpu usage, no any other answers from Bind method.
All works fine using ldap port (389) without encription.
AD server configured for using ldaps.
Certificates verification ignored on client (LDAPTLS_REQCERT=never )
Same problem when i use ldapsearch, but if i set option maxssf (-O maxssf=200) all works fine.
I suggest if i set  maxssf in LdapForNet before bind i would bind successfully, but SetOption not works without Bind (There is call  method ThrowIfNotBound() before settting options as i see), i got error "LdapForNet.LdapException: Not bound. Please invoke Bind method before"

I try to setup SASL_SECPROPS maxssf=<factor> in /etc/ldap/ldap.conf and it had not affected LDapForNet behavior.
My question is how can i specify option LDAP_OPT_X_SASL_SSF_MAX via this LdapForNet  library?

**Comment by flamencist** [comment]
Hi! Unfortunately sasl set options are not supported. But I have a plan to add method SetSaslOption.
