### ISSUE TITLE
Can not retrieve objetSid from LdapEntry

### ISSUE THREAD

**Issue by beppler** [flamencist/ldap4net#11]
After get an LdapEntry I can not retrieve the correct value for objectSid attribute coming from AD.

It is a binary value and is being copied as if it is a string [here](https://github.com/flamencist/ldap4net/blob/master/LdapForNet/RequestHandlers/SearchRequestHandler.cs#L76).

**Comment by flamencist** [comment]
Hi! It is known issue. But I plan to add GetValues<T> method to each retrieved attribute with allowed types: byte[] and string

**Comment by flamencist** [comment]
I add generic GetValues method for retrieving directory attribute's value. It will become available in the next version. So you need to use the modern generic method ```SendRequestAsync```
for example: 
```c#
            using (var connection = new LdapConnection())
            {
...
                var response = (SearchResponse)await connection.SendRequestAsync(new SearchRequest("cn=admin,dc=example,dc=com", "(&(objectclass=top)(cn=admin))", LdapSearchScope.LDAP_SCOPE_SUBTREE), CancellationToken.None);
                var directoryAttribute = response.Entries.First().Attributes["objectSid"];
                var objectSid = directoryAttribute.GetValues<byte[]>().First();
            }
```
