### ISSUE TITLE
Active Directory not working 

### ISSUE THREAD

**Issue by murattdogan** [flamencist/ldap4net#111]
how to use Active Directory login examples

**Comment by flamencist** [comment]
Start with examples https://github.com/flamencist/ldap4net#bind
Also your client machine dhould be joined to domain or use simple/basic/digest auth

**Comment by murattdogan** [comment]
Server Off. Result: 81. Method: ldap_connect

**Comment by murattdogan** [comment]
https://github.com/Nordes/IdentityServer4.LdapExtension  and config appsetting 
I ran this project with these settings.
```
{
  "IdentityServerLdap": {
    // Example: If you use a redis instead of in-memory (See Startup.cs)
    //"redis": "localhost:32771,ssl=false",
    //"RefreshClaimsInSeconds": 3600,
    "Connections": [
      {
        // //-------------------------------------------------------------------------
        // //Active directory
        // //-------------------------------------------------------------------------
        //"ldapActiveDirectory": {
        //  "Url": "79.123.184.30",
        //  "port":389,
        //  "ssl": false,
        //  //"bindDn": "cn=ldap-ro,dc=contoso,dc=com",
        //  "bindDn": "Hitit\\Administrator",
        //  "bindCredentials": "DmN!!HTT2019HTT!!12357bidb",
        //  //"searchBase": "cn=users,dc=hitit,dc=edu,dc=tr",
        // "searchBase": "DC=hitit,DC=edu,DC=tr",
        //  "searchFilter": "(&(objectClass=user)(sAMAccountName={0}))",
        //  //"searchFilter": "(&(objectClass=user)(objectClass=person)(sAMAccountName={0}))", // <== AD specific (users object are also different than OpenLdap)
        //  // Example: If you use a redis instead of in-memory
        //  "redis": "localhost:32771,ssl=false"
        //}
      },
      {


        "FriendlyName": "Active directory",
        "Url": "İpAdress",
        "Port": 389,
        "Ssl": false,
        "BindDn": "Hitit\\Administrator",
        "BindCredentials": "Password",
        "SearchBase": "DC=hitit,DC=edu,DC=tr",
        "SearchFilter": "(&(objectClass=user)(sAMAccountName={0}))",
        "PreFilterRegex": "^(?![a|A]).*$" // not mandatory and will take everything not starting with A
      }
      //,
      //{
      //  "FriendlyName": "OpenLdap-BuzzUsers",
      //  "Url": "localhost",
      //  "Port": 389,
      //  "Ssl": false,
      //  "BindDn": "cn=ldap-ro,dc=contoso,dc=com",
      //  "BindCredentials": "P@ss1W0Rd!",
      //  "SearchBase": "ou=users-buzz,DC=contoso,dc=com",
      //  "SearchFilter": "(&(objectClass=posixAccount)(objectClass=person)(uid={0}))",
      //  "PreFilterRegex": "^([a|A]).*$" // not mandatory and will take everything not starting with A
      //}
    ]
  }

  // -------------------------------------------------------------------------
  // Retro-compatibility, in case you want to use only one configuration.
  // -------------------------------------------------------------------------
  // Openldap
  // -------------------------------------------------------------------------
  //"LdapOpenLdap": {
  //  "url": "localhost",
  //  "port": 389,
  //  "ssl": false,
  //  "bindDn": "cn=ldap-ro,dc=contoso,dc=com",
  //  "bindCredentials": "P@ss1W0Rd!",
  //  "searchBase": "ou=users,DC=contoso,dc=com",
  //  "searchFilter": "(&(objectClass=posixAccount)(objectClass=person)(uid={0}))" // <== OpenLdap specific (users object are also different than AD)
  //},
  // -------------------------------------------------------------------------
  // Active directory
  // -------------------------------------------------------------------------
  //"ldapActiveDirectory": {
  //  "url": "localhost",
  //  "port": 389,
  //  "ssl": false,
  //  "bindDn": "cn=ldap-ro,dc=contoso,dc=com",
  //  "bindCredentials": "P@ss1W0Rd!",
  //  "searchBase": "cn=users,dc=contoso,dc=com",
  //  "searchFilter": "(&(objectClass=user)(objectClass=person)(sAMAccountName={0}))", // <== AD specific (users object are also different than OpenLdap)
  //  // Example: If you use a redis instead of in-memory
  //  "redis": "localhost:32771,ssl=false"
  //}
}
```

**Comment by flamencist** [comment]
The error means that server is not available. Check hostname/ipaddress and port. The port 389 should be available via telnet/nc.

using (var cn = new LdapConnection())
{
	// connect use hostname and port
	cn.Connect("IpAddress",389);
	....
}

**Comment by murattdogan** [comment]
An item with the same key has already been added. Key: subschemaSubentry

**Comment by murattdogan** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using LdapForNet;
using static LdapForNet.Native.Native;
namespace LdapForNetExample
{
    class Program
    {
        private static string ADPath = "LdapServerİpAdres";
        private static string ADUser = "Administrator";
        private static string ADUser2 = "Hitit\\Administrator";
        private static string ADPassword = "Password";
        private static string ADServer = "hitit.edu.tr";
        private static string BaseDc = "dc=hitit,dc=edu,dc=tr";
        private static string Fillter = "(&(objectClass=user)(sAMAccountName=muratdogan))";
        static void Main(string[] args)
        {
            var cmds = ParseCommandLine(args);
            cmds.TryGetValue("host", out var host);
            cmds.TryGetValue("auth", out var authString);
            cmds.TryGetValue("base", out var @base);
            cmds.TryGetValue("filter", out var filter);
            cmds.TryGetValue("port", out var portStr);
            int.TryParse(portStr, out var port);
            var auth = authString == LdapAuthMechanism.GSSAPI ? LdapAuthMechanism.GSSAPI : LdapAuthMechanism.SIMPLE;
            host = host ?? "LdapServerİpAdres";
            @base = @base ?? "dc=hitit,dc=edu,dc=tr";
            filter = filter ?? "(&(objectClass=user)(objectClass=*)";
            port = port > 0 ? port : 389;

            try
            {
                var token = new CancellationTokenSource();
                Console.CancelKeyPress += (sender, eventArgs) => token.Cancel();
                while (!token.IsCancellationRequested)
                {
                    UsingOpenLdap(auth, host, @base, port, filter, cmds).Wait();
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
            Console.WriteLine("End");
        }

        private static Dictionary<string, string> ParseCommandLine(string[] args)
        {
            var pattern = "^--([^=\"]*)=\"?(.*)\"?$";
            return args.Select(_ => Regex.Matches(_, pattern, RegexOptions.IgnoreCase).Cast<Match>().FirstOrDefault()?.Groups)
                .Where(_ => _ != null)
                .ToDictionary(_ => _[1].Value, _ => _[2].Value);
        }

        private static async Task UsingOpenLdap(string authType, string host, string @base, int port, string filter, IDictionary<string, string> cmds)
        {
            Console.WriteLine($"{nameof(authType)}:{authType}; {nameof(host)}:{host}; {nameof(@base)}:{@base}; {nameof(port)}:{port} ");
            using (var cn = new LdapConnection())
            {
                cn.Connect(host, port);
                if (authType == LdapAuthMechanism.GSSAPI)
                {
                    await cn.BindAsync();
                }
                else
                {
                    cmds.TryGetValue("who", out var who);
                    cmds.TryGetValue("password", out var password);
                    who = who ?? "Hitit\\Administrator";
                    password = password ?? "Password";
                    cn.Bind(LdapAuthMechanism.SIMPLE, who, password);
                    //cn.Bind(LdapAuthType.Anonymous, new LdapCredential
                    //{
                    //    UserName = who,
                    //    Password = password
                    //});
                }

                IList<LdapEntry> entries;

                if (cmds.TryGetValue("sid", out var sid))
                {
                    entries = await cn.SearchBySidAsync(@base, sid);
                }
                else
                {
                    var rootDse = cn.GetRootDse();
                    PrintEntry(rootDse);
                    var searchRequest = new SearchRequest(@base, filter,
                        LdapSearchScope.LDAP_SCOPE_SUBTREE)
                    {
                        AttributesOnly = false,
                        TimeLimit = TimeSpan.Zero,
                        Controls =
                        {
                            new PageResultRequestControl(500)
                            {
                                IsCritical = true
                            }

                        }
                    };
                    var searchResponse = ((SearchResponse)(await cn.SendRequestAsync(searchRequest)));
                    entries = searchResponse.Entries.Select(_ => _.ToLdapEntry()).ToList();
                }
                foreach (var ldapEntry in entries)
                {
                    PrintEntry(ldapEntry);
                }
            }
        }

        private static void PrintEntry(LdapEntry entry)
        {
            if (entry == null)
            {
                return;
            }
            Console.WriteLine($"dn: {entry.Dn}");
            foreach (var pair in entry.Attributes.SelectMany(_ => _.Value.Select(x => new KeyValuePair<string, string>(_.Key, x))))
            {
                Console.WriteLine($"{pair.Key}: {pair.Value}");
            }
            Console.WriteLine();
        }
    }
}

**Comment by flamencist** [comment]
Try to comment GetRootDse()

**Comment by murattdogan** [comment]
One or more errors occurred. (An item with the same key has already been added. Key: subschemaSubentry)

**Comment by flamencist** [comment]
Please put full stack of the exception
