### ISSUE TITLE
ldap login with user and password still reads current AD user's info in centos

### ISSUE THREAD

**Issue by qkevin** [flamencist/ldap4net#137]
**Describe the bug**
I tried to use user name and password to login in centos, but found an weird thing, it is still using current AD user's info to login.
  using (var cn = new LdapConnection())
            {
                cn.Connect("ldap://ldapservername:389");
                cn.Bind("GSSAPI", "abcd", "password");
                cn.WhoAmI();
                Console.WriteLine($"Host name:{cn.GetOption<string>(LdapForNet.Native.Native.LdapOption.LDAP_OPT_HOST_NAME)}");
                Console.WriteLine(await cn.WhoAmI());
            }
**To Reproduce**
it can be reproduced

**Expected behavior**
if login with a specified user then we should not use current AD user info.

**Desktop (please complete the following information):**
 - OS: centos7
 - Library version 2.7.13
 - .NET core 3.1
 - LDAP server [Active Directory]

**Additional context**

**Comment by flamencist** [comment]
We could not use a plain text password for kerberos (gssapi) auth on linux platform. Its ignored for your case. That is worked for digest or simple auth only. Please change auth for using text passwords

**Comment by qkevin** [comment]
thanks a lot for your reply, that makes sense to me.

**Comment by PavelRubis** [comment]
> We could not use a plain text password for kerberos (gssapi) auth on linux platform. Its ignored for your case. That is worked for digest or simple auth only. Please change auth for using text passwords

Hello @flamencist . Could u pls explain why it is impossible to bind via GSSAPI Kerberos with clear text creds (on linux)? Openldap native libraries don't support this? Just failed searching answer for this in web..
