### ISSUE TITLE
[Question] Parallel requests

### ISSUE THREAD

**Issue by BalassaMarton** [flamencist/ldap4net#138]
Is LdapConnection thread-safe, eg. can I make multiple async requests in parallel? Specifically I want to run multiple searches in parallel, but I guess it would be the same for other requests.

**Comment by flamencist** [comment]
Yes. The library is based on openldap on unix systems and native ldap on windows. These underlying libraries are thread safe

**Comment by BalassaMarton** [comment]
Awesome, thanks.
