### ISSUE TITLE
Support for libldap 2.5

### ISSUE THREAD

**Issue by fubar-coder** [flamencist/ldap4net#141]
**Is your feature request related to a problem? Please describe.**

I'd like to use this library on recent Linux distributions. Ubuntu 21.10 - for example - doesn't ship libldap-2.4-2 anymore.

**Describe the solution you'd like**

It would be useful to make this library work with libldap-2.4-2 and libldap-2.5-0 (and maybe libldap-2.6-0, issue #140).

A workaround could be to implement the native APIs for every LDAP version. If the changes are trivial (e.g. structs with new fields at the end), then the same code could be reused, but the native library probing should be reworked (dllmap or something similar).

**Describe alternatives you've considered**

I tried to add a link from libldap-2.4.so.2 to libldap-2.5.so.0 and liblber-2.4.so.2 to liblber-2.5.so.0, but I got an assert, which indicates changes to the API. Another workaround was to install an old ubuntu (libldap-2.4-2_2.4.45+dfsg-1ubuntu1.10_amd64.deb) package, which seems to work, but looks like a temporary solution.

**Additional context**

**Comment by flamencist** [comment]
Hi! It is big gap. I think that need add few new shims for those versions. So most simple solution to implement next native shim for those libraries. I will appreciate if someone helps in this way.
