### ISSUE TITLE
Works fine on Windows 10, but not on Windows server 2008 r2

### ISSUE THREAD

**Issue by feigaogit** [flamencist/ldap4net#15]
Works fine on Windows 10, but not on Windows server 2008 r2,
![image](https://user-images.githubusercontent.com/18181270/71860036-2bb7a880-312c-11ea-9439-9b02b988fa9f.png)

![image](https://user-images.githubusercontent.com/18181270/71859987-f01cde80-312b-11ea-92bd-5f365c547b8f.png)
May I ask what caused it

**Comment by flamencist** [comment]
Could please provide exception message and stack trace?

**Comment by feigaogit** [comment]
The .netnetframwork version upgrade to 4.7.1 has been resolved
