### ISSUE TITLE
Any way to mock SearchResponse

### ISSUE THREAD

**Issue by sam-mfb** [flamencist/ldap4net#157]
I'm trying to test some logic that makes calls to `SendRequestAsync`.  I can mock the call into `SendRequestAsync` and vary the return based on inspection of the `SearchRequest` object passed.  But I can't  figure out a way to have it return a mocked (or real) version of a `SearchResponse`--specifically it's `Entries` field.  That field's setter is marked as `internal` so it can't be called outside of the assembly, and there is no constructor that allows setting `Entries`.  

See the definition [here](https://github.com/flamencist/ldap4net/blob/2076ad7c90aa2e4e35c3e1d7f04f2b21636e92a4/LdapForNet/DirectoryResponse.cs#L59)

Is there anyway to address this in testing?

**Comment by flamencist** [comment]
you could use 
```
var response = new SearchResponse();
response.Entries.Add(new DirectoryEntry{ Dn = "", ... });

```

**Comment by sam-mfb** [comment]
Right; that makes sense.  I must not have had enough copy this morning.  WIll give that a try.
