### ISSUE TITLE
`LdapSizeLimitExceededException` when performing search with `SizeLimit`

### ISSUE THREAD

**Issue by BalassaMarton** [flamencist/ldap4net#176]
**Describe the bug**
This seems to be not an actual bug in LdapForNet, but an error in either libldap or the server itself. When sending  a `SearchRequest` with its `SizeLimit` set, `SendRequestAsync` throws a `LdapSizeLimitExceededException`. Debugging into it revealed that the status code returned by `ldap_parse_result` is `SizeLimitExceeded` even though the server actually returned the correct number of entries. LdapForNet should swallow this error.

This find was part of a larger investigation, I will submit a pull request in the coming days to fix it.

**To Reproduce**

```cs
var response = await ldapConnection.SendRequestAsync(
    new SearchRequest(dn, filter, searchScope, attributes) { SizeLimit = sizeLimit };
```

**Expected behavior**
`SendRequestAsync` should succeed and response should contain `sizeLimit` number of entries.

**Desktop (please complete the following information):**
 - OS: RHEL 7.9
 - Library version: 2.7.15
 - .NET\core\mono version: .NET 6
 - LDAP server: (redacted)

**Comment by BalassaMarton** [comment]
Cool, thanks :)

**Comment by flamencist** [comment]
Yesterday I pressed a wrong button)) Thank you for contribution
