### ISSUE TITLE
Cannot Connect

### ISSUE THREAD

**Issue by gokhantiknaz** [flamencist/ldap4net#2]
Hi sir. I'm using Vs2019 on windows.
When i try to connect open ldap server i'm getting this error.

What am i doing wrong ?

{"Unable to load DLL 'ldap-2.4.so.2' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}

Here is my code.

 using (var connection = new LdapConnection())
                {
                    connection.Connect(Config.LdapHost, Config.LdapPort);
                    connection.Bind(LdapAuthMechanism.SIMPLE, Config.LdapUserDn, Config.LdapPassword);
                    var entries = connection.Search(Config.RootDn, "(&(objectclass=top)(cn=admin))");

                    return true;
                }

**Comment by flamencist** [comment]
Hi! The library worked on linux platform only. But I plan to port on windows in future.

**Comment by flamencist** [comment]
Library is ported to all platforms

**Comment by gokhantiknaz** [comment]
> Library is ported to all platforms

Thank you my friend. It'll be very usefull for me
