### ISSUE TITLE
I'm having trouble getting Kerberos auth working on Linux

### ISSUE THREAD

**Issue by Alethon** [flamencist/ldap4net#20]
In the README, you say 

> For Linux\OSX you must ensure you have the latest OpenLDAP client libraries installed from http://www.openldap.org

Would you mind specifying some (Debian-based) package names? My program works fine on windows, but BindKerebos fails every time from Ubuntu.

**Comment by flamencist** [comment]
You should install libldap package
``` sudo apt-get install libldap-2.4-2 ```

**Comment by Alethon** [comment]
Thank you! I'll comment again and close the issue if it works

**Comment by Alethon** [comment]
It worked! I also needed to install krb5-user for kerberos support, but it worked flawlessly otherwise.
