### ISSUE TITLE
Is there a way to securely authenticate User1 using a Kerberos ticket from User2?

### ISSUE THREAD

**Issue by Alethon** [flamencist/ldap4net#21]
I am presently writing what amounts to a linux-based Active Directory proxy for authentication (I authenticate against AD then use AD group membership for API authorization).

With my current configuration, I use `kinit <username>` to get and store a (static) Kerberos ticket for an Active Directory user. `BindKerebos` uses this ticket to send LDAP requests to Active Directory, ignoring any supplied username and password. 

Is there a way I can securely bind using a provided username and password combination?

(Edit: I guess I'm asking if you've implemented SASL yet.)

**Comment by flamencist** [comment]
Currently i am working on implementation sasl proxy authorization for the library

**Comment by flamencist** [comment]
I implemented [SASL proxy authorization](http://www.openldap.org/doc/admin24/sasl.html#SASL%20Proxy%20Authorization). It's available in next version [2.3.0](https://www.nuget.org/packages/LdapForNet/2.3.0). As I know SASL proxy authorization is supported in openldap server. And MS Active Directory is not supported SASL proxy authorization. But you could use DIGEST-MD5 or Simple authentication for MS AD.

**Comment by Alethon** [comment]
Thank you!

**Comment by Alethon** [comment]
Just so you know, I checked
