### ISSUE TITLE
How to perform paged SearchRequest queries?

### ISSUE THREAD

**Issue by Thomas-Avery** [flamencist/ldap4net#23]
Hi does this library support paged directory queries? 

I see SizeLimit on the SearchRequest object but only see values  0<x<1000 for SizeLimit = x actually having a result. 

Any x greater than 1000, only 1000 objects are returned from the directory.

**Comment by flamencist** [comment]
Hello! It's implemented but not released yet. You could track the issue status or project task https://github.com/flamencist/ldap4net/projects/1

**Comment by Thomas-Avery** [comment]
Awesome, is there anything I could do to help out?

**Comment by flamencist** [comment]
I will appreciate if you can help project. So need test suite for PageResultRequestControl\PageResultResponseControl. Now used openldap server for tests on linux\osx, but I have'not such on windows.

**Comment by v2kiran** [comment]
Hi @flamencist - Thank you for making this.
 Will the pagedsearch feature be available any time soon?

**Comment by flamencist** [comment]
Will be available in version 2.5. ETA - 4-6 weeks

**Comment by v2kiran** [comment]
great thanks for the quick response!

**Comment by Zubastic** [comment]
@flamencist this is control is major problem for enterprise use now. For Novell I did custom PageResultRequestControl, any workaround for current version? I guess, implementation of ExtendedRequest could help with that?

**Comment by flamencist** [comment]
No. You can not setup control via ExtendedRequest. Support of ldap v3 controls will be added to next version 2.5. Wait please.
