### ISSUE TITLE
Reset password for other user.

### ISSUE THREAD

**Issue by bekamgeladze** [flamencist/ldap4net#24]
Hello, is there way to reset other user password using your library. I need implement changing user password in Windows Active Directory with .net core application hosted on Linux server. If this is possible please write some example for it. Thank you in advance.

**Comment by flamencist** [comment]
Microsoft AD uses [unicidePwd attribute by default](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/6e803168-f140-4d23-b2d3-c3a8ab5917d2). It's offical way to change password in AD.
I wrote example using the library: [reset password](https://gist.github.com/flamencist/45ecead51bed9089c50ee1c6ef5cf577)
But need to use modify operation with binary values and it will be available in next version only.
Also AD supports [userPassword attribute](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/f3adda9f-89e1-4340-a3f2-1f0a6249f1f8). But need to [set the fUserPwdSupport heuristic is true in the dSHeuristics](https://ldapwiki.com/wiki/Enable%20UserPassword%20in%20Microsoft%20Active%20Directory).

**Comment by bekamgeladze** [comment]
Thank you.

**Comment by mharrisn** [comment]
Hello is there any ETA on when the new version will be pushed to NuGet? Any chance of a pre-release? We support multiple platforms with .net core and this seems to be the cleanest, most elegant LDAP lib available. Thank you!

**Comment by flamencist** [comment]
I will plan 1-2 weeks to deploy new version with necessary changes
