### ISSUE TITLE
Suggestion: Native.LdapAuthType.Anonamous for Bind

### ISSUE THREAD

**Issue by Reelix** [flamencist/ldap4net#25]
With the default LDAP classes, you could go

```
ldapConnection.AuthType = AuthType.Anonymous;
```
Your current version equivalent is
```
LdapCredential anonymousCredential = new LdapCredential();
ldapConnection.Bind(Native.LdapAuthType.Simple, anonymousCredential);
```

I suggest a
```
ldapConnection.Bind(Native.LdapAuthType.Anonymous);
```

version to simplify migration.

**Comment by flamencist** [comment]
Yes. Will be available in next version. https://github.com/flamencist/ldap4net/blob/6d5d67a5859cc9e205a886e8b6d6634b4c2b3bec/LdapForNet/LdapConnection.cs#L67
