### ISSUE TITLE
thumbnailPhoto to Image

### ISSUE THREAD

**Issue by VSDekar** [flamencist/ldap4net#30]
Is there a sample on how i have to convert an image (thumbnailPhoto Attribute) back to an image?

Would be nice if you could provide a sample or push me into the right direction.

**Comment by flamencist** [comment]
Images are stored in binary format in ldap services. You could retrieve binary values from image and create image. Example: https://github.com/flamencist/ldap4net#search-attributes-with-binary-values
```
using (var cn = new LdapConnection())
{
	cn.Connect();
	cn.Bind();
	var response = (SearchResponse) connection.SendRequest(new SearchRequest("cn=admin,dc=example,dc=com", "(&(objectclass=top)(cn=admin))", LdapSearchScope.LDAP_SCOPE_SUBTREE));
	var directoryAttribute = response.Entries.First().Attributes["photo"];
	var objectSid = directoryAttribute.GetValues<byte[]>().First();
}
```

**Comment by VSDekar** [comment]
Thanks a lot. Worked perfectly. 👍👍

Sorry that i overlooked the sample in the ReadMe.
