### ISSUE TITLE
ldap_get_option

### ISSUE THREAD

**Issue by Zubastic** [flamencist/ldap4net#32]
**Is your feature request related to a problem? Please describe.**
Now I couldn't get some options of connection directly via ldap_get_option.

**Describe the solution you'd like**
Make method ldap_get_option in connection class. Or maybe make LdapNative field in connection class protected, so anybody could inherit base class and use additional api of LdapNative functions.

**Comment by flamencist** [comment]
Thank you for feature request. What exactly options do you need? Please provide some example.

**Comment by Zubastic** [comment]
Well, connection have method SetOption, but you couldn't get them back.
