### ISSUE TITLE
Replace DirectoryOperationException from DirectoryServices

### ISSUE THREAD

**Issue by elodou01** [flamencist/ldap4net#44]
**Is your feature request related to a problem? Please describe.**
I am currently working on a program using DirectoryServices.Protocols, and I am trying to replace everything related to this package with the LdapForNet solution.
How can I replace DirectoryOperationExceptions ? Is it implemented yet ? 

**Describe the solution you'd like**
For example 
`try{
_something_
}
catch(DirectoryOperationException);`

I don't think that using LdapExceptions will be correct here.

**Comment by flamencist** [comment]
Use LdapOperationException as replacement

**Comment by elodou01** [comment]
Thank you a lot !
