### ISSUE TITLE
LdapOptions

### ISSUE THREAD

**Issue by elodou01** [flamencist/ldap4net#47]
**Is your feature request related to a problem? Please describe.**
I would like to replace the options from DirectoryServices with LdapForNet options.

Here is my code : 
```
connection.SessionOptions.Sealing = true;

connection.SessionOptions.Signing = true;

connection.SessionOptions.VerifyServerCertificate = new VerifyServerCertificateCallback((con, cer) => true); 

connection.SessionOptions.QueryClientCertificate = new QueryClientCertificateCallback((con, trustedCAs) => null); 
```

**Describe the solution you'd like**
How can I use LdapForNet to set those options ? And with which options ? 
I already use `connection.SetOption(LdapForNet.Native.Native.LdapOption.LDAP_OPT_SSL, 1);` for example

**Comment by flamencist** [comment]
Hi!
```connection.SessionOptions.VerifyServerCertificate = new VerifyServerCertificateCallback((con, cer) => true); ```  used for connection with self signed certificate. 
You could use for it 
https://github.com/flamencist/ldap4net#connect-ssl-with-self-signed-certificate 
```c#
 cn.TrustAllCertificates(); 
```
or https://github.com/flamencist/ldap4net#connect-tls
  set argument to true for tls 
```c#
cn.StartTransportLayerSecurity(true);  
```

```connection.SessionOptions.Signing = true; ``` is windows specific and  cannot be used over an SSL connection.
So you could set using
 ```c#
var signing = 1;
cn.SetOption(LdapOption.LDAP_OPT_SIGN, ref signing);
```
Also ```connection.SessionOptions.Sealing = true;``` is windows specific too and cannot be used over an SSL connection. 
It is equivalent
```c#
var encrypt = 1;
cn.SetOption(LdapOption.LDAP_OPT_ENCRYPT, ref encrypt);
```
 https://github.com/flamencist/ldap4net#setoption

**Comment by flamencist** [comment]
Option ```LdapOption.LDAP_OPT_SSL``` is set automatically if you use SSL or TLS connection
https://github.com/flamencist/ldap4net#connect-tls
https://github.com/flamencist/ldap4net#connect-ssl-with-self-signed-certificate

**Comment by elodou01** [comment]
Thank you ! 
What about the `QueryClientCertificateCallback` ? Is there something equivalent ?

**Comment by flamencist** [comment]
```QueryClientCertificateCallback``` is used for external authentication. No need to set ```null``` value. Example of using https://github.com/flamencist/ldap4net#bind-sasl-external-client-certificate--active-directory

**Comment by elodou01** [comment]
Perfect, thank you a lot :)
