### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by elodou01** [flamencist/ldap4net#49]
**Describe the bug**
Hi ! I need to use a `DirectoryAttribute` and convert it into strings but when I do it I have wrong values.
For example, if I convert a `DirectoryAttribute` into a string and back into a `DirectoryAttribute`, it won't have the same values. I am using a GUID like beneath :

**To Reproduce**
```
attribute = entry.Attributes["name"];
attribute.GetValues<string>().ToList();
var bytes = Encoding.ASCII.GetBytes(Values[0]);
var guid = new Guid(bytes).ToString("N", CultureInfo.InvariantCulture);
```
where `attribute` is a DirectoryAttribute.

The `bytes` object is only 15 bytes long whereas I need 16 bytes to create a GUID. My `attribute ` object is 16 bytes long so there is no reason for the `bytes` not to be 16 bytes long.

**Comment by flamencist** [comment]
Hi! Your encoding is not correct. Use Utf8Encoding. UTF8 is standard for LDAP v3.

**Comment by flamencist** [comment]
Also you could create Guid with bytes
 ```c#
public Guid? GetGuid(byte[] bytes) 
            => bytes != null && bytes.Length == 16 ? (Guid?) new Guid(bytes) : null;
```

**Comment by elodou01** [comment]
Ok thank you, I found another solution.
Instead of using `attribute.GetValues<string>().ToList()` I used `attribute.GetValues<string>().FirstorDefault()`. That solved my probleme
