### ISSUE TITLE
Conversion fails in SendRequest

### ISSUE THREAD

**Issue by elodou01** [flamencist/ldap4net#56]
**Describe the bug**
Hi ! I am having trouble using a `SendRequest`, I have the following exception:
```
Error running send request: 00000057: LdapErr: DSID-0C0910B5, comment: Error in attribute conversion operation, data 0, v47ba
```

**To Reproduce**
The error message is contained in my `response `:
```
var response = connection.SendRequest(request);
if (response.ResultCode != LdapForNet.Native.Native.ResultCode.Success)
{
      throw new Exception("Error running send request: " + response.ErrorMessage);
}
```
The `request `is an `AddRequest` and the `connection ` is inherited from an `LdapConnection`. More specifically, it is a pooled Ldap connection (you can find few documentation on google about it).
I am using a `Bind()` method for my connection, and an Anonymous authType.

I really don't understand where a conversion is done and why it fails. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Library version : 2.5

**Comment by flamencist** [comment]
Provide please data sample. Looks like attribute's values are wrong. Check attribute's values. For example: values of objectClass should have known names: organizationalPerson instead of organizationPerson and so on.

**Comment by elodou01** [comment]
Thank you for your answer. Unfortunately, I can't provide you any data sample. 
I checked my attributes and some of it are null, I believe that the conversion error comes from those attributes.
