### ISSUE TITLE
Can't reach ldap server localhost without http://

### ISSUE THREAD

**Issue by elodou01** [flamencist/ldap4net#58]
**Describe the bug**
Hi !
I would like to connect to my `localhost:5389` server. The connection is okay but the binding will fail with a `ServerDown` error.

**To Reproduce**
```
var server = "localhost:5389"
using var connection = new LdapConnection();
connection.Connect(server);
connection.Bind(LdapAuthType.Negotiate, credential);
```

When I use `server = "http://localhost:5389"` the binding is successful. 
Why can't I bind on the localhost without http or https ? 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Library version : 2.7.1
 - .NET\core\mono version : 3.1
 - LDAP server : ActiveDirectory

**Comment by flamencist** [comment]
What?!
Do bind to http server. Ldap has own protocols.

**Comment by flamencist** [comment]
check documentation https://github.com/flamencist/ldap4net#connect

**Comment by elodou01** [comment]
Ok, I only needed to use `connection.Connect("localhost", 5389)`, I was trying to do much more complicated than that 
Can I use it without connection like I can with `Connect(server)` ? The method doesn't seem to be existing, but I would like to do this `Connect("localhost", 5389)` alone

**Code sample**
```
            var server = new UriBuilder(directory).Uri;
            if (server.Host == null || server.Host.Length == 0)
            {
                Connect("localhost",5389));
            }
            else
            {
                Connect(directory);
            }
```
The first Connect isn't working

**Comment by flamencist** [comment]
First example should work
```
using var connection = new LdapConnection();
connection.Connect("localhost",5389);
```

**Comment by elodou01** [comment]
That would not work because I am in a class that is inherited from LdapConnection
So I need to proceed the `Connect ` on the object in itself, not a new one

**Code sample** 
```
    internal sealed class PooledLdapConnection : LdapConnection
    {
        private readonly ILdapPool pool;
        private readonly LdapChannel channel;
        public PooledLdapConnection(ILdapPool pool, LdapChannel channel)
            : base()
        {
            this.pool = pool;
            this.channel = channel;

            var server = new UriBuilder(channel.Directory).Uri;
            if (server.Host == null || server.Host.Length == 0)
            {
                Connect("localhost", 5389));
            }
            else
            {
                Connect(channel.Directory);
            }
        }
   }
```
and after that I can easily do the `SetOption()` and `Bind()` methods without a connection

**Comment by flamencist** [comment]
You could use 
```
Connect(new Uri("LDAP://localhost:5389"), LdapVersion.LDAP_VERSION3)
```

**Comment by elodou01** [comment]
I could, but I am actually getting the port and hostname through the server (`server.Port` for example), so I cannot know in advance which port I will be using

**Comment by flamencist** [comment]
So you could use ```Connect(uriFromServer, LdapVersion.LDAP_VERSION3)```
