### ISSUE TITLE
URI scheme

### ISSUE THREAD

**Issue by mattlindstrom** [flamencist/ldap4net#59]
![image](https://user-images.githubusercontent.com/9418997/86034344-0717fb80-ba00-11ea-9269-9285a770273b.png)

Cannot connect via IP:Port?

Exception thrown:  System.UirFormatException: 'Invalid URI:  The URI Scheme is not valid.'

Examples:
234.34.34.344:389
LDAP://234.44.44.545:389

**Comment by flamencist** [comment]
Check documentation https://github.com/flamencist/ldap4net#connect
```
using (var cn = new LdapConnection())
{
	// connect use hostname and port
	cn.Connect("dc.example.com",636);
	....
}
```
or use URI
```
using (var cn = new LdapConnection())
{
	// connect with URI
	cn.Connect(new URI("ldaps://dc.example.com:636"));
	....
}
```

**Comment by mattlindstrom** [comment]
Having problems with the namespace for "URI":

![image](https://user-images.githubusercontent.com/9418997/86035605-3e87a780-ba02-11ea-98ee-3305d392719a.png)


And the second argument appears to be looking for a LdapVersion, not Port:

![image](https://user-images.githubusercontent.com/9418997/86035725-6840ce80-ba02-11ea-884c-ad864e357254.png)


Am I referencing the incorrect package(s)?

**Comment by flamencist** [comment]
It's extensions methods. Please reference 
```
using LdapForNet;
```
or use directly

**Comment by mattlindstrom** [comment]
I created a new .cs file with the same code minus the Novell.Directory.Ldap references/imports I had (which will be getting replaced by LdapForNet eventually) and now the intellisense shows all 3 overloads:

![image](https://user-images.githubusercontent.com/9418997/86040164-25cec000-ba09-11ea-8655-075a969c09c8.png)

Thanks for your help!
