### ISSUE TITLE
Search doesnt work on Linux

### ISSUE THREAD

**Issue by v2kiran** [flamencist/ldap4net#65]
**Describe the bug**
Search for objects dose not work on linux(ubuntu 18.04).

**To Reproduce**
```powershell
add-type -AssemblyName /mnt/c/Users/kiranna/Source/LdapForNet.dll
$cn = [LdapForNet.LdapConnection]::new()
$cn.Connect("ldap://server.example.com:389",[LdapForNet.Native.Native+LdapVersion]::LDAP_VERSION3)
$base = "dc=example,dc=com"
$filter = "(&(objectcategory=person)(name=kiran*))"
$ldapcred = [LdapForNet.LdapCredential]::new()
$ldapcred.UserName = "admin"
$ldapcred.Password = "password"
$ldapcred.Realm = "example.com"
$cn.Bind([LdapForNet.Native.Native+LdapAuthType]::Digest,$ldapcred)
$cn.Search($base,$filter,"Name",[LdapForNet.Native.Native+LdapSearchScope]::LDAP_SCOPE_SUBTREE)
```

**Expected behavior**
The search function completes showing the returned objects.

**Actual behavior**
The search function seems to get stuck and never returns or times out.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Library version :2.7.2
 - .NET\core\mono version - netstandard 2.0
 - LDAP server : Active Directory

**Additional context**
The search works perfectly fine on windows with the same ldap server its only on linux that its failing.
Also the search works with ad lds on linux so something seems to be going wrong specifically with AD.I have also tried changing the ad server but same result. Perhaps I am missing some parameter or setting something incorrectly on linux.
Would appreciate an example where it works with AD on linux.

**Comment by flamencist** [comment]
Do you use powershell core?

**Comment by v2kiran** [comment]
Using powershell 7

**Comment by flamencist** [comment]
Is host **server.example.com** available? Is it ping-ed?

**Comment by flamencist** [comment]
I've checked  and the script is worked on ubuntu 20.94

**Comment by v2kiran** [comment]
Yup I did make sure DNS resolution and ping were both working. I also changed the server just to make sure it wasn't a server issue.

Did you use the exact same parameters in your test or did you have to change anything?

**Comment by flamencist** [comment]
I replaced Realm to empty string, used Simple auth method and changed username to cn=admin,dc=example,dc=com

**Comment by v2kiran** [comment]
Ok thx...I will try these out and see if it works

**Comment by v2kiran** [comment]
based on your input i created a new linux VM(ubuntu 20.04). Installed openldap libs.
Tried to connect and now get this:
```
MethodInvocationException: Exception calling "Connect" with "2" argument(s): 
"Unable to load shared library 'ldap-2.4.so.2' or one of its dependencies. 
In order to help diagnose loading problems, consider setting the LD_DEBUG 
environment variable: 
/snap/core18/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found 
(required by /lib/x86_64-linux-gnu/libldap-2.4.so.2)"
```

i checked the glibc version on ubuntu 20.04 and it seems to be the higher version than what is required.
```
PS /opt/gitent> ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9) 2.31
```

it dosent seem like the 2.28 package exists anymore so I am not sure how to get this to work on 20.04

**Comment by flamencist** [comment]
Is ldapsearch or ldapwhoami worked ?

**Comment by flamencist** [comment]
I have installed libldap library via apt 
```sudo apt install libldap-2.4-2```
It's located in ```/usr/lib/x86_64-linux-gnu/libldap-2.4.so.2```

**Comment by v2kiran** [comment]
ldapsearch works.(tested with 2 different domains)
I installed openldap via this
```
sudo apt install slapd ldap-utils
```

i also verified that that lib  exists:
```
$ ls -l /usr/lib/x86_64-linux-gnu/libldap-2.4.so.2
lrwxrwxrwx 1 root root 18 Jun 12 15:18 /usr/lib/x86_64-linux-gnu/libldap-2.4.so.2 -> libldap_r-2.4.so.2
```

**Comment by flamencist** [comment]
Good. How you launch powershell script ? From terminal ?

**Comment by v2kiran** [comment]
I installed powershell via snap because on 20.04 thats the only supported method.
then I just do :
`pwsh` and start typing( no script used)

**Comment by flamencist** [comment]
But I install powershell using apt
```sudo apt-get install -y powershell```

**Comment by v2kiran** [comment]
Ok I guess while it's not supported we could still get it via apt-get...
Will remove the snap package and retry with apt-get.

**Comment by v2kiran** [comment]
this is weird:

```bash
$ sudo apt-get install -y powershell
Reading package lists... Done
Building dependency tree
Reading state information... Done

No apt package "powershell", but there is a snap with that name.
Try "snap install powershell"

E: Unable to locate package powershell
$ sudo add-apt-repository universe
'universe' distribution component is already enabled for all sources.
```

i guess i will wait for another week when Microsoft is expected to add support for Ubuntu 20.04 for powershell 7.1

**Comment by vossjannik** [comment]
I have the same or at least a similar problem on Arch Linux with 2.7.2 of this library. I was also able to reproduce the problem with a modified version of your PowerShell script. As in your example, the bind request works fine but the search request seems to get stuck. In my case, it always succeeds eventually after around 10 seconds. I tried to analyze the issue using Wireshark on the windows server where AD is running. The search request is received immediately and the answer is send back within milliseconds. The search result contains 1 entry and 3 referrals. I think the problem has to do with the referrals, but the problem does not go away if I do:

```
    // by default, referrals are followed. disable that.
    connection.SetOption(LdapOption.LDAP_OPT_REFERRALS, 0);
```

I was able to suppress this problem (at least for now) because in my use case I only need the first search result and already know that it exists. This is how I exit the search early:

```
        public LdapEntry LookupOne(string baseDN, string filter, string[] attributes = null)
        {
            using var cts = new CancellationTokenSource();
            var results = new List<DirectoryEntry>();
            var directoryRequest = new SearchRequest(baseDN, filter, LdapSearchScope.LDAP_SCOPE_SUB, attributes)
            {
                OnPartialResult = searchResponse =>
                {
                    if (searchResponse.Entries.Count != 0)
                    {
                        // one entry is enough. stop parsing the search request.
                        // this can prevent strange timeout with referrals because the entries are usually parsed
                        // before the referrals are followed.
                        results.AddRange(searchResponse.Entries);
                        cts.Cancel();
                    }
                }
            };

            var response = (SearchResponse)connection.SendRequestAsync(directoryRequest, cts.Token).Result;
            return response.Entries.FirstOrDefault()?.ToLdapEntry();
        }
```

**Comment by flamencist** [comment]
@vossjannik Do you catch the issue from dotnet app ? And what powershell do you use and how to installed ?

**Comment by vossjannik** [comment]
@flamencist I can reproduce it in a C# application and with a Powershell script like the one above. I don't think this problem is specific to Powershell. I'll try to find out more in the upcoming days. Anyway, I am using Arch linux with this package: https://aur.archlinux.org/packages/powershell-bin/

```
% pwsh --version
PowerShell 7.0.3

% yay -Q --info powershell-bin
Name            : powershell-bin
Version         : 7.0.3-1
Description     : A cross-platform automation and configuration tool/framework (binary package)
Architecture    : x86_64
URL             : https://github.com/Powershell/Powershell
Licenses        : None
Groups          : None
Provides        : powershell
Depends On      : krb5  gcc-libs  glibc  lttng-ust  zlib  openssl-1.0  icu
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : powershell
Replaces        : None
Installed Size  : 151.00 MiB
Packager        : Unknown Packager
Build Date      : Wed 16 Sep 2020 10:35:43 PM CEST
Install Date    : Wed 16 Sep 2020 10:35:48 PM CEST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None

% yay -Ss powershell-bin
aur/powershell-bin 7.0.3-1 (+36 1.91%) (Installed)
    A cross-platform automation and configuration tool/framework (binary package)
```

**Comment by v2kiran** [comment]
@vossjannik  - thanks for chiming in.

@flamencist  - I had someone test the PowerShell code on a mac with the username as a DN and auth as "simple" and they reported seeing the same behavior. The console just hangs. 

So yeah it dosent seem to be related to the way PowerShell was installed. It may be related to refferals because the library works well with AD LDS on both windows as well as linux it is just with AD that it is having this issue. 

Note: On windows I created a powershell module written in c# where I disabled the refferals with:
`  connection.SetOption(LdapOption.LDAP_OPT_REFERRALS, 0);`

then I imported the binary(*.dll) module on linux and it had the same issue. so disabling referrals didn't help solve the issue on linux but it did speed up the results on windows :) .

**Comment by gergodrazsdik** [comment]
I had issues with referrals on linux. I found out, that the correct way to disable them on linux is:
`connection.SetOption(Native.LdapOption.LDAP_OPT_REFERRALS, IntPtr.Zero);`

On windows it was working for me either way.

**Comment by vossjannik** [comment]
@gergodrazsdik's solution works for me. Tested on both Linux and FreeBSD.

**Comment by flamencist** [comment]
@v2kiran is solution @gergodrazsdik  worked for you?

**Comment by v2kiran** [comment]
@flamencist  - Yes it did 😃 on linux Ubuntu 18.04
I was waiting to test it on a Mac but I am sure it will work there too.

@gergodrazsdik  - thank you for posting the solution.

**Comment by v2kiran** [comment]
the mac user came back and said it worked there as well.
mac os: 10.15
powershell: 6.2
i think we can close this issue now.
