### ISSUE TITLE
Allow Change password in Active Directory

### ISSUE THREAD

**Issue by jaredrsowers** [flamencist/ldap4net#68]
In order to do a modify password in Active Directory (not admin reset) you need to create a single request with a Delete and then an Add of unicodePwd (https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/6e803168-f140-4d23-b2d3-c3a8ab5917d2). 

But, since `ModifyAttributeCollection` inherits from `KeyedCollection<string, DirectoryAttribute>` it does not allow adding 2 attributes with the same name.

What is the purpose for this instead of having it inherit from something like `List<DirectoryModificationAttribute>`?

I would be willing to do a pull request, but this is a potential breaking change...

```

var oldPasswordAttribute = new DirectoryModificationAttribute
{
    Name = "unicodePwd",
    LdapModOperation = Native.LdapModOperation.LDAP_MOD_DELETE
};

oldPasswordAttribute.Add(Encoding.Unicode.GetBytes($"\"{oldPassword}\""));

var newPasswordAttribute = new DirectoryModificationAttribute
{
    Name = "unicodePwd",
    LdapModOperation = Native.LdapModOperation.LDAP_MOD_ADD
};

newPasswordAttribute.Add(Encoding.Unicode.GetBytes($"\"{newPassword}\""));

var response = await _ldapConnection.Value.SendRequestAsync(new ModifyRequest(userDistinguishedName, oldPasswordAttribute, newPasswordAttribute));

```

**Comment by jaredrsowers** [comment]
And there is the option of doing something like this so that it has the same method signatures:

```
public class ModifyAttributeCollection : List<DirectoryModificationAttribute>
{
    public bool Contains(string name) =>
        this.Any(x => String.Equals(x.Name, name, StringComparison.OrdinalIgnoreCase));

    public DirectoryAttribute this[string name]
    {
        get
        {
            var item = this.FirstOrDefault(x => String.Equals(x.Name, name, StringComparison.OrdinalIgnoreCase));

            if (item == null)
            {
                throw new KeyNotFoundException();
            }

            return item;
        }
    }

    public bool TryGetValue(string name, out DirectoryAttribute item)
    {
        item = this.FirstOrDefault(x => String.Equals(x.Name, name, StringComparison.OrdinalIgnoreCase));

        if (item == null)
        {
            return false;
        }

        return true;
    }

    public bool Remove(string name)
    {
        var found = false;

        for (int i = 0; i < Count; i++)
        {
            if (String.Equals(this[i].Name, name, StringComparison.OrdinalIgnoreCase))
            {
                RemoveAt(i);
                --i;

                found = true;
            }
        }

        return found;
    }
}
```

**Comment by flamencist** [comment]
Yes, using indexer is good option. Could you please add change to the pull request?

**Comment by JManou** [comment]
Hello, I think that the bug was introduced with this PR #61 , the GetKeyItem of the ModifyAttributeCollection was changed.

**Comment by jaredrsowers** [comment]
@JManou, It doesn't look like it. #61 just added `StringComparer.OrdinalIgnoreCase`. The problem is inheriting from `KeyedCollection` because it does not allow for 2 items of the same key.

**Comment by flamencist** [comment]
@JManou FYI search attribute collection reverted to dictionary
