### ISSUE TITLE
ToLdapEntity messes with binary data

### ISSUE THREAD

**Issue by axelgenus** [flamencist/ldap4net#72]
**Describe the bug**
ToLdapEntry method messes up with binary values in such a way that they are not reversible.

**To Reproduce**
- Convert a DirectoryEntry to LdapEntry;
- convert the LdapEntry back to DirectoryEntry;
- compare the same attribute binary value.

**Expected behavior**
I would expect the two methods to retain the same data among conversions.

**Environment:**
 - OS'es: Windows and Linux (Docker containers)
 - Library version: 2.7.4
 - .NET Core 3.1
 - LDAP server: Active Directory

**Additional context**
This is quite an issue if you're using Search methods and you need to get binary attributes (e.g. objectSid or objectGuid). Also the SID conversion routines are internal so, if you're using SendRequest, you cannot make use of them for searching by objectSid.

I prepared a small NUnit test case for this: https://gist.github.com/axelgenus/622eca57b4e6218f0789136671a5cf72

Also, I ported from LDAP-wiki a very handy routine to get the objectSid SDDL string representation: https://gist.github.com/axelgenus/a9872a8bb57e3d3fa614dab3b9fa0b86

It would be nice if you could include both in LdapForNet.

**Comment by flamencist** [comment]
Thank you for reply! I will look

**Comment by flamencist** [comment]
Use could use method ```DirectoryEntry.GetObjectSid``` for retrieving objectSid in string format
