### ISSUE TITLE
Missing Platform Detection for FreeBSD

### ISSUE THREAD

**Issue by vossjannik** [flamencist/ldap4net#76]
**Describe the bug**
We plan to use this library on FreeBSD, but the platform detection mechanism is not implemented for FreeBSD.
Since .NET 5.0 Preview 8 and .NET Core 3.1 3.0 the OSPlatform enum contains this new value:

`public static System.Runtime.InteropServices.OSPlatform FreeBSD { get; }`
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.osplatform.freebsd?view=netcore-3.1

**Current behavior**
A PlatformNotSupportedException is thrown.

**Expected behavior**
The platform should be identified correctly.

**Potential problem**
The current target framework of this library is `netstandard2.0;netstandard2.1`.  Since the FreeBSD enum value is not supported by any .Net Standard version, `netcoreapp3.0` should probably be added as a target.

**Code snippets**

```
            if (RuntimeInformation.IsOSPlatform(OSPlatform.FreeBSD))
            {
                return new UnixEncoder();
            }
```
```
            if (RuntimeInformation.IsOSPlatform(OSPlatform.FreeBSD))
            {
                return new LdapNativeLinux();
            }
```

**Comment by flamencist** [comment]
I don't know that unix version should worked on freebsd. Could you please build and run tests of ldap4net on freebsd using unix version?

**Comment by vossjannik** [comment]
#90
