### ISSUE TITLE
PInvokeStackImbalance exception thrown by using with .NET Framework 

### ISSUE THREAD

**Issue by aboldarev** [flamencist/ldap4net#8]
I'm trying to use this lib in .NET Standard 2.0 dll. It seems to work with a dotnetcore projects, but brakes if i use it in .NetFramework

PInvokeStackImbalance' : 'A call to PInvoke function 'LdapForNet!LdapForNet.Native.NativeMethodsWindows::ldap_init' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

**Comment by flamencist** [comment]
Could you please provide the details for reproduction?

**Comment by flamencist** [comment]
I could not to reproduce. 
I use:
Windows 10 with .net4.6.1,.net4.8

**Comment by aboldarev** [comment]
I’m using a Win10 x64 also. 
I have made test application with a docker support. You should be able to get an exception, when you just run a project 

https://github.com/aboldarev/ldap4net


![image](https://user-images.githubusercontent.com/14258642/66653820-2506bb80-ec39-11e9-99b6-55c8125f7759.png)

**Comment by aboldarev** [comment]
you can try to change a calling conversion 
        [DllImport(LIB_LDAP_PATH, CallingConvention = CallingConvention.Cdecl)]

**Comment by flamencist** [comment]
Hi, @aboldarev  I could not reproduce on your examples. Could you please check again with my latest changes https://github.com/flamencist/ldap4net/tree/issue/stack-imbalance ?
