### ISSUE TITLE
Better use of exceptions

### ISSUE THREAD

**Issue by esavini** [flamencist/ldap4net#80]
**Is your feature request related to a problem? Please describe.**
Use of `LdapException` for every problem is not the best way to expose an error (we need to compare the `ResultCode`).

**Describe the solution you'd like**
An exception for every result code (ex. LdapInvalidCredentialsException, LdapUnavailableException, etc). 

```csharp
try
{
    // Connection
}
catch (LdapUnavailableException exception)
{
    // Do something
}
```

**Describe alternatives you've considered**
Currently the code is like this.

```csharp
try
{
    // Connection
}
catch (LdapException exception) when (exception.ResultCode == Native.ResultCode.Unavailable)
{
    // Do something
}
```

**Comment by flamencist** [comment]
Yes its good idea. I think we could inherits new type of exceptions from base ```LdapException```.
