### ISSUE TITLE
Unable to create mock of list of LdapEntry values due to internal constructor for SearchResultAttributeCollection

### ISSUE THREAD

**Issue by dougbelkofer** [flamencist/ldap4net#87]
**Description of the Problem**
I am creating unit tests that need to mock (using the Moq library) various parts of LdapForNet. I have an interface (ILapService) and implementation (LdapService) between my application and LdapForNet. In order to unit LdapService, I need to be able to mock what LdapForNet returns. To be specific, I want to set up my unit test such that a call to SearchAsync returns a list of LdapEntry objects that I have created in advance of the call.

I can easily create multiple LdapEntry instances and put them in a list, but I'm having trouble setting up their DirectoryAttribute values, because I cannot create a new SearchResultAttributeCollection instance to assign to the DirectoryAttributes property of the LdapEntry instance, because the constructor for SearchResultAttributeCollection uses the internal access modifier. Also, the LdapEntry class has no constructors defined, so the default generated by the compiler will leave the DirectoryAttributes property set to null.

Because of this, my unit test code throws a NullReferenceException when I'm trying to add DirectoryAttribute objects to the DirectoryAttributes property using it's Add method,

**To Reproduce**
Here is the relevant code
```
        private void SetupUserSearchOneUser(string dn)
        {
            // Next line creates a new LdapEntry instance, no constructor is defined, so
            // compiler generated default leaves the DirectoryAttributes property as null
            var entry = new LdapEntry();
            // Can't do this next line because the constructor has internal access modifier
            //entry.DirectoryAttributes = new SearchResultAttributeCollection();

            entry.Dn = dn;
            AddNewDirectoryAttribute(entry, "distinguishedName", dn);
            AddNewDirectoryAttribute(entry, "accountExpires", "0x7FFFFFFFFFFFFFFF");
            AddNewDirectoryAttribute(entry, "pwdLastSet", "0x0");
            AddNewDirectoryAttribute(entry, "userAccountControl", "512");
            // purposely leaving off logonHours


            var list = new List<LdapEntry> { entry };

            this.mockLdapConnection.Setup(m => m.SearchAsync(It.IsAny<string>(),
                                                             It.IsAny<string>(),
                                                             It.IsAny<string[]>(),
                                                             Native.LdapSearchScope.LDAP_SCOPE_SUB,
                                                             new CancellationToken())).ReturnsAsync(list);
        }

        private void AddNewDirectoryAttribute(LdapEntry e, string name, string value)
        {
            var dirAttr = new DirectoryAttribute();
            dirAttr.Name = name;
            dirAttr.Add(value);
            // This next line throws the NullReferenceException because e.DirectoryAttributes is null.
            e.DirectoryAttributes.Add(dirAttr);
        }
```
**Expected behavior**
I expect to be able to manually construct LdapEntry objects with DirectoryAttribute instances in the DirectoryAttributes property for use in unit testing. I see two possible ways to address this:

1.  Change the access modifier of the SearchResultAttributeCollection constructor to public.

OR

2.  Add a constructor to the LdapEntry class that initializes the DirectoryAttributes property using the existing SearchResultAttributeCollection constructor, leaving the access modifier as is.

I'd be more than happy to clone the repo, make either of these changes (I lean towards #2 being the better option), and then create a pull request.

**Desktop (please complete the following information):**
 - OS: Windows, but will also be running on Linux
 - Library version [e.g. 2.3] 2.7.6
 - .NET\core\mono version [e.g. 4.6, 3.1] .NET Core 3.1
 - LDAP server [e.g. Active Directory, OpenLdap] Active Directory

**Additional context**
This code is part of an IdentityServer4 based service that provides authentication & authorization services within our enterprise, and is part of a project to host this service in a Linux Kubernetes cluster. Development occurs under Windows, but some testing and production use will be hosted in the Linux Kubernetes cluster.

**Comment by flamencist** [comment]
Fixed in last version

**Comment by flamencist** [comment]
@dougbelkofer Did you check in last version?
