### ISSUE TITLE
Package does not have a strong name

### ISSUE THREAD

**Issue by vossjannik** [flamencist/ldap4net#92]
**Describe the bug**
I am unable to reference the LdapForNet package in an application that is strongly signed.
`
CSC : error CS8002: Referenced assembly 'LdapForNet, Version=2.7.10.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
`

**To Reproduce**
Reference this package in a project that uses strong name signing. You cannot reference unsigned assembly from a signed assembly.

**Expected behavior**
The package should be strongly signed.

**Desktop (please complete the following information):**
 - OS: Windows, Linux, and FreeBSD
 - Library version 2.7.10
 - .NET Core 3.1

**Additional information**
I am currently using the following package as a workaround:
`<PackageReference Include="Brutal.Dev.StrongNameSigner" Version="2.7.1" />`

**Comment by flamencist** [comment]
I don't have expirience with a strong name. Do you know what needs to do?

**Comment by vossjannik** [comment]
Signing an assembly with a strong name is necessary if you want to load multiple versions of the same assembly. Strong-named assemblies require all their dependencies to be signed as well. This is why I need it.

I think you don't have to do much more than checking a box in the project settings and select/generate a key file:
https://docs.microsoft.com/en-us/dotnet/standard/assembly/sign-strong-name

For open source projects it is okay to commit both the private and the public key to the repository. The strong-name only provides a unique name, and should not be relied upon for security.
Source:
https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named
> If you are an open-source developer and you want the identity benefits of a strong-named assembly for better compatibility with .NET Framework, consider checking in the private key associated with an assembly to your source control system.

**Comment by sej69** [comment]
This will become an issue for me, too.  Google's packages at one point were not signed either so I ended up downloading the source, compiling, and applying my certificate to sign the libraries.  But I'd prefer just being able to download your library directly through nuget.  It's actually quite easy to sign packages...

**Comment by jepperc** [comment]
Also having an issue, can't use the package without it.
Can I make a PR to fix? The current guidelines suggest they key should just be in the repository, so should be easy 🙂

**Comment by flamencist** [comment]
Yes, you can

**Comment by thj-dk** [comment]
@flamencist any chance of having @jepperc PR #131 merged?
