### ISSUE TITLE
ILdapConnection does not contain async methods

### ISSUE THREAD

**Issue by gregbair** [flamencist/ldap4net#94]
**Describe the bug**
Although `LdapConnection` contains async versions of add, delete, and modify, the `ILdapConnection` interface does not.

**To Reproduce**
```c#
ILdapConnection conn = new LdapConnection();

// connect and bind
await conn.AddAsync(params)
```
Does not compile.

**Expected behavior**
These methods to exist on the interface

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Catalina
 - Library version [e.g. 2.3]: 2.4.0
 - .NET\core\mono version [e.g. 4.6, 3.1] core 3.1
 - LDAP server [e.g. Active Directory, OpenLdap] OpenLdap

**Comment by flamencist** [comment]
I'll look

**Comment by gregbair** [comment]
I can take a stab at it.

**Comment by gregbair** [comment]
Any idea when this will be released? We had to put in a hack for this.

**Comment by flamencist** [comment]
Released
